### ISSUE TITLE
Default or implicitly defined attributes on pydantic model should be persisted on create operations

### ISSUE THREAD

**Issue by littlebeeper** [volfpeter/motorhead#12]
- We might have some default values on the pydantic model ( E.g. type attribute for an entity type)
- These should be serialized/dumped as mongo compatible data on inserts

**Comment by volfpeter** [comment]
@littlebeeper Please have a look at the linked PR. Let me know if this is sufficient for you use-case. The default behavior is what you requested.

I'll merge the PR and publish a new release after completing the remaining ToDos in the PR. Until then you can install motorhead from the PR branch.

**Comment by littlebeeper** [comment]
Looks good @volfpeter Thank you

**Comment by volfpeter** [comment]
Having thought about it, this issue can be considered not only an enhancement but also a bug fix (and no breaking change): defaults should be stored in the database during creation, otherwise if the Pydantic model changes (e.g. the default is replaced), then all previously created documents can be considered invalid.

There are other use-cases for default values, when you may want the old behavior. For users who need that, `Service.service_config` must be set.
